server:
  port: 8083    # HTTP(Tomcat) Port，端口自定义

spring:
  datasource:
    username: afadmin
    password: afadmin
    url: jdbc:oracle:thin:@192.168.5.209:6521:orcl
    driver-class-name: oracle.jdbc.OracleDriver

Login:
  username: admin
  password: admin

  #  username: root
   #   password: 123456
    #  url: jdbc:mysql://localhost:3306/upbus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai #数据库连接池（druid）
     # driver-class-name: com.mysql.cj.jdbc.Driver # 加载Driver驱动